team: devops_team
component_name: fluent-bit
escalation_policy: DevOps Escalation Policy
business_region:
  - AMER
environment:
  - INT
  - UAT
  - SBX
  - PRO
aliases:
  - fluent-bit
  - FLUENT-BIT
  - fluent_bit
external_id: fluent-bit
