team: devops_team
component_name: karpenter
escalation_policy: DevOps Escalation Policy
business_region:
  - AMER
  - EMEA
environment:
  - INT
  - UAT
  - SBX
  - PRO
aliases:
  - karpenter
  - KARPENTER
external_id: karpenter
