team: devops_team
component_name: merchant-gateway-batch
escalation_policy: DevOps Escalation Policy
depends_on:
  - DB-PWMB
business_region:
  - AMER
  - EMEA
environment:
  - INT
  - UAT
  - SBX
  - PRO
aliases:
  - merchant-gateway-batch
  - MERCHANT-GATEWAY-BATCH
  - merchant_gateway_batch
external_id: merchant-gateway-batch
