team: devops_team
component_name: prometheus-ops
escalation_policy: DevOps Escalation Policy
business_region:
  - AMER
  - EMEA
environment:
  - INT
  - UAT
  - SBX
  - PRO
aliases:
  - prometheus-ops
  - PROMETHEUS-OPS
  - prometheus_ops
external_id: prometheus-ops
