team: devops_team
component_name: redis
escalation_policy: DevOps Escalation Policy
business_region:
  - AMER
  - EMEA
environment:
  - INT
  - UAT
  - SBX
  - PRO
aliases:
  - redis
  - REDIS
external_id: redis
