team: devops_team
component_name: cronjobs
escalation_policy: DevOps Escalation Policy
business_region:
  - AMER
  - EMEA
environment:
  - INT
  - UAT
  - SBX
  - PRO
aliases:
  - cronjobs
  - CRONJOBS
external_id: cronjobs
