team: devops_team
component_name: nginx-edge
escalation_policy: DevOps Escalation Policy
business_region:
  - AMER
  - EMEA
environment:
  - INT
  - UAT
  - SBX
  - PRO
aliases:
  - nginx-edge
  - NGINX-EDGE
  - nginx_edge
external_id: nginx-edge
