team: integration
name: Support and Operations
description: Support & Operations Team
escalation_policy:
  time_zone: America/Sao_Paulo
  levels: 3
  minutes_between_levels: 15
  loops: 9
external_id: integration_team
aliases:
  - integration
  - INTEGRATION
tech_lead: "null"
members:
  - "null"
non-production_channel: '#null'
production_channel: '#null'
manager: "null"
